import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import PrimaryAppBar from "./components/Header";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Electrical Equipment Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <PrimaryAppBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
