import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import PrimaryAppBar from "@/components/Header";
import QueryProvider from "@/utils/queryProvider";
import { CartProvider } from "@/contexts/cart";
import { UserProvider } from "@/contexts/user";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Electrical Equipment Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryProvider>
          <UserProvider>
            <CartProvider>
              <PrimaryAppBar />
              <main>{children}</main>
            </CartProvider>
          </UserProvider>
        </QueryProvider>
        <ToastContainer position="top-center" autoClose={3000} closeOnClick />
      </body>
    </html>
  );
}
